### PR TITLE
web: adapt to new treeherder jobdetail API

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
For this change to work, changes will need to deployed to treeherder production. For now, you can test this by setting `TREEHERDER_API` to https://treeherder.allizom.org/api

**Comment by mnoorenberghe** [comment]
Thanks @wlach! I'll take a look at this later since it seems like there are some indentation-only changes which make it look more complicated than it is.
Do you know if this change is backwards compatible with old jobs? i.e. after this change will I be able to fetch the artifacts from before the TH change (e.g. 2 months ago)?

**Comment by wlach** [comment]
Yeah sorry I may have messed up the indentation in a few places, not used to 2-space. But yes, this change is backwards compatible. We converted all the old job info artifacts to the new format.

**Comment by mnoorenberghe** [comment]
X-ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1278597

I pushed 040a5066f14b936b4a7355e459209352da1b2f3c to fix the python script which also caused issues.

**Comment by mnoorenberghe** [comment]
Fixed in 621b194fed8ab6aabd0eb72f4acb261f2ac260df

**Pull request closed without merging**
